### ISSUE TITLE
bwallet-cli: view fails

### ISSUE THREAD

**Issue by gtklocker** [bcoin-org/bclient#12]
```
» ./bwallet-cli view "77b24a0102054ca6a046e2fb61c59fe274a38a562dabcd2df24ad9e3ed8b2716"
TypeError: this.wallet.fill is not a function
    at CLI.viewTX (/home/vagrant/bcash-interlinker/node_modules/bclient/bin/bwallet-cli:352:34)
    at CLI.handleWallet (/home/vagrant/bcash-interlinker/node_modules/bclient/bin/bwallet-cli:569:20)
    at CLI.open (/home/vagrant/bcash-interlinker/node_modules/bclient/bin/bwallet-cli:682:17)
    at /home/vagrant/bcash-interlinker/node_modules/bclient/bin/bwallet-cli:693:13
    at Object.<anonymous> (/home/vagrant/bcash-interlinker/node_modules/bclient/bin/bwallet-cli:695:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by gtklocker** [comment]
Aparrently due to `WalletClient.fill(_)` not existing.

**Comment by pinheadmz** [comment]
I just stumbled on to this myself @tuxcanfly @nodar-chkuaselidze the help menu for `view` says:

```
  $ view [tx-hex]: Parse and view transaction.
```

But bclient is calling `fill()` which is not a method! What's this call supposed to do? It's not in the API docs
